classDiagram
dirction TB



class EngineCore{
    - model_executor: Executor
    - scheduler: SchedulerInterface
}

EngineCore o-- Executor: model_executor
EngineCore o-- SchedulerInterface: scheduler

class CoreEngineActorManager{
    - executor_class : Executor
    - created_placement_groups: list
    - run_refs[] : DPEngineCoreActor
}

%% rank와 client의 주소를 저장하고 관리 하는 클래스
class MPClient{
    - resource : BackgroundResources
    - encoder : MsgpackEncoder
    - decoder : MsgpackDecoder
    - input_socket : zmq
}

%% ZeroMQ
class zmq 
class AsyncEngineArgs
class AsyncLLM{
    - vllm_config : VllmConfig
    - tokenizer : TokenizerGroup
    - processor : Processor
    - output_processor : OputputProcessor
    - engine_core : MPClient
    
    + from_engine_args(AsyncEngineArgs)
}

MPClient o-- MsgpackEncoder: encoder
MPClient o-- MsgpackDecoder: decoder
MPClient o-- zmq

class AsyncMPClient{
    - outputs_queue[] : EngineCoreOutputs
}

AsyncMPClient o-- EngineCoreOutputs : 

class BackgroundResources{
    + engine_manager : Union[CoreEngineProcManager,CoreEngineActorManager]
    + coordinator : DPCoordinator
    + output_socket : zmq
}

class OpenAIServingCompletion{
    + engine_client : EngineClient
}

class Scheduler{
    - vllm_config: VllmConfig,
    - kv_cache_config: KVCacheConfig,
}
class SchedulerInterface

Scheduler--|>SchedulerInterface

OpenAIServingCompletion--|>OpenAIServing
OpenAIServingCompletion o-- EngineClient: engine_client

AsyncLLM o-- VllmConfig : vllm_config
AsyncLLM o-- TokenizerGroup: tokenizer
AsyncLLM o-- Processor: processor
AsyncLLM o-- OputputProcessor: output_processor
AsyncLLM o-- MPClient: engine_core

EngineCoreClient<|--MPClient
DPAsyncMPClient--|>AsyncMPClient
DPAsyncMPClient<|--DPLBAsyncMPClient

MPClient<|--AsyncMPClient
MPClient o-- BackgroundResources

dataclass <|-- EngineArgs
EngineArgs <|--AsyncEngineArgs

AsyncLLM-->AsyncEngineArgs
EngineClient <|--AsyncLLM

BackgroundResources o-- DPCoordinator : coordination
BackgroundResources o-- CoreEngineProcManager: engine_manager
BackgroundResources o-- CoreEngineActorManager: engine_manager
BackgroundResources o-- zmq: output_socket

CoreEngineActorManager o-- Executor: executor_class
CoreEngineActorManager o-- DPEngineCoreActor: run_refs

DPEngineCoreActor--|>DPEngineCoreProc
DPEngineCoreProc--|>EngineCoreProc
EngineCoreProc--|>EngineCore